apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java-spring-template
  title: Java Spring Boot Template
  description: Scaffolds a Java Spring Boot app with Docker and Jacoco support, pushes to new repo
spec:
  owner: team@example.com
  type: service
  parameters:
    - title: Project Info
      required: ['projectName', 'owner', 'javaVersion', 'buildTool']
      properties:
        projectName:
          type: string
          title: Project Name
        owner:
          type: string
          title: GitHub Owner (org or user)
        javaVersion:
          type: string
          title: Java Version
          enum: ['17', '21']
        buildTool:
          type: string
          title: Build Tool
          enum: ['maven', 'gradle']
  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          projectName: "{{ parameters.projectName }}"
          javaVersion: "{{ parameters.javaVersion }}"
          buildTool: "{{ parameters.buildTool }}"
    - id: publish
      name: Publishing to a github repository
      action: publish:github
      input:
        repoUrl: https://github.com/{{ parameters.owner }}/{{ parameters.projectName }}
        defaultBranch: main
        description: "Generated Java Spring Boot app"
        repoVisibility: public
