apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.projectName }}
  namespace: ${{ values.projectName }}
  labels: 
    entity-id: ${{values.projectName}}
    app: ${{values.projectName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.projectName }}
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: ${{ values.projectName }}
        entity-id: ${{values.projectName}}
        app: ${{ values.projectName }}
    spec:
      serviceAccountName: ${{ values.projectName }}
      containers:
      - name: ${{ values.projectName }}
        image: ${{ values.projectName }}:0.1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"  
            cpu: "100m"       
          requests:
            memory: "128Mi"  
            cpu: "50m"    
