apiVersion: v1
kind: Service
metadata:
  name: ${{ values.projectName }}
  namespace: ${{ values.projectName }}
  labels:
    backstage.io/kubernetes-id: ${{ values.projectName }}
spec:
  selector:
    app: ${{ values.projectName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
