apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.projectName }}
  description: Java Spring Boot app
  tags:
    - java
    - springboot
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
