FROM eclipse-temurin:{{ javaVersion }}-jdk-jammy

WORKDIR /app

COPY . .

{{#if (eq buildTool "maven")}}
RUN ./mvnw clean package -DskipTests
CMD ["java", "-jar", "target/{{projectName}}-0.0.1-SNAPSHOT.jar"]
{{else}}
RUN ./gradlew build -x test
CMD ["java", "-jar", "build/libs/{{projectName}}-0.0.1-SNAPSHOT.jar"]
{{/if}}
